### 넘파이(NumPy) : 배열(ndarray , n dimension array)

* 리스트(List) : Linked List 구조(불연속), 동작 속도가 느리다, comma로 요소 구별, 서로 다른 자료형을 사용할 수 있다
* 배열(ndarray) : 연속된 메모리 구조, 동작 속도가 빠르다, comma를 사용하지 않고 공백으로 요소 구별, 오직 한 가지의 타입만 갖을수 있다 

In [8]:
import numpy as np 
# pip install numpy 

# List
list1 = [0,1,2,3,4,5]
print(list1)
print(type(list1))

# 리스트를 사용해서 ndarray 생성
a = np.array([0,1,2,3,4,5])  # 요소의 자료형을 동일하게 사용
print(a)
print(type(a))    # ndarray
print(a.dtype)    # 요소의 자료형

[0, 1, 2, 3, 4, 5, 'k', (1, 2)]
<class 'list'>
[0 1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [11]:
# Shift + Tab : 함수 나 모듈 및 변수 객체 위에 커서를 놓고 프로토 타입을 볼수 있다

In [20]:
# int 와 float  ---> float
a = np.array([0,1,2.,3,4])
print(a)
print(type(a))
print(a.dtype)

[0. 1. 2. 3. 4.]
<class 'numpy.ndarray'>
float64


In [21]:
# int / float  + str  ---> Unicode string
a = np.array([0,1,2.,3,'Hello'])
print(a)
print(type(a))
print(a.dtype)   # <U32 :  리틀엔디언, 유니코드, 최대 문자 32 byte

# 유니코드 인코딩 방식
# (1) EUC-KR , CP949(MS949) : 완성형, 한글 2바이트, 영문은 1바이트 , Windows
# (2) UFT-8 : 조합형, 한글 3 바이트, 영문은 1 바이트, Linux

['0' '1' '2.0' '3' 'Hello']
<class 'numpy.ndarray'>
<U32


In [22]:
# numpy 의 dtype 객체의 종류 : 대소문자 모두 사용가능
np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'bool8', 'Bool', 'b1', 'int64', 'Int64', 'i8', 'uint64', 'Uint64', 'u8', 'float16', 'Float16', 'f2', 'float32', 'Float32', 'f4', 'float64', 'Float64', 'f8', 'complex64', 'Complex32', 'c8', 'complex128', 'Complex64', 'c16', 'object0', 'Object0', 'bytes0', 'Bytes0', 'str0', 'Str0', 'void0', 'Void0', 'datetime64', 'Datetime64', 'M8', 'timedelta64', 'Timedelta64', 'm8', 'int32', 'Int32', 'i4', 'uint32', 'UInt32', 'u4', 'UInt64', 'int16', 'Int16', 'i2', 'uint16', 'UInt16', 'u2', 'int8', 'Int8', 'i1', 'uint8', 'UInt8', 'u1', 'complex_', 'int0', 'uint0', 'single', 'csingle', 'singlecomplex', 

In [30]:
# 배열의 데이터 타입 변환 : astype()
a1 = np.array(['1.234','3.123','4.4356','5','7'])
print(a1,a1.dtype)    # <U6 : 리틀엔디언, 유니코드, 최대 문자 6 byte

a2 = a1.astype('float32')
print(a2,a2.dtype)

a3 = a2.astype('int32')
print(a3,a3.dtype)

['1.234' '3.123' '4.4356' '5' '7'] <U6
[1.234  3.123  4.4356 5.     7.    ] float32
[1 3 4 5 7] int32


### 차원 과 Shape

* 차원(Dimension, Rank) : 1,2,3차원,n차원, 첫 데이터까지의 대괄호의 갯수
* Shape : 차원의 요소들의 수, 튜플형식
##### 1 차원 Shape  : ( x, )
##### 2 차원 Shape  : ( x, y)
##### 3 차원 Shape  : ( x,y,z )
     ....
##### n차원 Shape  : ( x,y,z,........ )      

In [47]:
# 1차원 배열의 Shape
# arange(start,end + 1,step)
a = np.arange(12)
print(a,type(a))
print(a.shape)   # (12,)
t = a.shape
print(type(t))   # tuple
print(a.shape[0])

a2 = np.arange(2,10)
print(a2,type(a2))
print(a2.shape)   # (8,)

a3 = np.arange(0,16,2)
print(a3,type(a3))
print(a3.shape)   # (8,)

[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'>
(12,)
<class 'tuple'>
12
[2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
(8,)
[ 0  2  4  6  8 10 12 14] <class 'numpy.ndarray'>
(8,)


In [60]:
# 2차원 배열의 Shape  : 행(row,가로, 수직,  axis = 0) 과 열(column,세로,수평,axis = 1)  
m = np.array([np.arange(3),np.arange(3)])
# m = np.array([[0, 1, 2],[0, 1, 2]])
print(m)
print(m.shape)   # (2,3)
print(m.shape[0],m.shape[1])

[[0 1 2]
 [0 1 2]]
(2, 3)
2 3


In [36]:
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [57]:

m = np.arange(3)
m

array([0, 1, 2])